#!/bin/sh

if [ -z "$1" ] ; then
    echo "usage: $0 <file>"

    echo "Did you create a tag on the master recently for this REV?"
    echo "Please branch a new REV after this tag"
    echo "";
    echo "git checkin"
    echo "git checkout master, merge, etc"
    echo "git tag <rev>"
    echo "make-dist <ibcli>"
    echo "(this will also make docs and relnotes)";
    echo "";
    echo "update the web pages";
    echo "git checkout gh-pages";
    echo "git merge, push, etc";
    echo "";
    echo "git checkout -b <new-rev>"
    echo "";

    exit ;
fi


GIT=/usr/bin/git

# hack in some RCS tagging stuff so we know what rev is in the file
REV=`$GIT describe --tag`
LOG=`$GIT log -n 1 --pretty=format:'%cD %an' $1`

# i'm using my own RCS tagging here, so I can use better syntax
perl -pi.orig \
    -e "s/:Id:.*::/:Id: $LOG ::/;" \
    -e "s/:Revision:.*::/:Revision: $REV ::/;" \
    $1

echo "$REV $LOG";

# make the release notes etc
./make-relnotes
./make-docs


